---
- name: Create a new instance for the Loom worker.
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include: tasks/gcloud_create_instance.yml

- name: Configure SSH key on Loom worker.
  hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  become_user: loom
  become_method: su
  tasks:
  - include: tasks/gcloud_configure_instance_ssh.yml

- name: Set up new instance(s).
  hosts: new_instances
  remote_user: loom
  become_method: su
  become: yes

  roles:
  - {role: docker, when: "not {{lookup('env', 'WORKER_SKIP_INSTALLS')}}"}
  - {role: docker-py, when: "not {{lookup('env', 'WORKER_SKIP_INSTALLS')}}"}
  - loom-worker
