---
- name: Create a new instance for the Loom worker.
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
  - boot_disk_size_gb: "{{lookup('env','WORKER_BOOT_DISK_SIZE')}}"
  - boot_disk_type: "{{lookup('env','WORKER_BOOT_DISK_TYPE')}}"
  - docker_full_name: "{{lookup('env','DOCKER_FULL_NAME')}}"
  - docker_tag: "{{lookup('env','DOCKER_TAG')}}"
  - gce_credential: "{{lookup('env','GCE_PEM_FILE_PATH')}}"
  - gce_email: "{{lookup('env','GCE_EMAIL')}}"
  - gce_ssh_key_file: "{{lookup('env', 'GCE_SSH_KEY_FILE')}}"
  - instance_image: "{{lookup('env','WORKER_VM_IMAGE')}}"
  - instance_name: "{{lookup('env','WORKER_INSTANCE_NAME')}}"
  - instance_type: "{{lookup('env','WORKER_INSTANCE_TYPE')}}"
  - log_level: "{{lookup('env','LOG_LEVEL')}}"
  - master_url: "{{lookup('env','MASTER_URL_FOR_WORKER')}}"
  - network: "{{lookup('env','WORKER_NETWORK')}}"
  - remote_user: "{{lookup('env', 'WORKER_REMOTE_USER')}}"
  - scratch_disk_device_path: "{{lookup('env','WORKER_SCRATCH_DISK_DEVICE_PATH')}}"
  - scratch_disk_mount_point: "{{lookup('env','WORKER_SCRATCH_DISK_MOUNT_POINT')}}"
  - scratch_disk_name: "{{lookup('env','WORKER_SCRATCH_DISK_NAME')}}"
  - scratch_disk_size_gb: "{{lookup('env','WORKER_SCRATCH_DISK_SIZE')}}"
  - scratch_disk_type: "{{lookup('env','WORKER_SCRATCH_DISK_TYPE')}}"
  - subnetwork: "{{lookup('env','WORKER_CUSTOM_SUBNET')}}"
  - tags: "{{lookup('env','WORKER_TAGS')}}"
  - task_run_attempt_id: "{{lookup('env', 'TASK_RUN_ATTEMPT_ID')}}"
  - task_run_docker_image: "{{lookup('env','TASK_RUN_DOCKER_IMAGE')}}"
  - use_internal_ip: "{{lookup('env','WORKER_USES_SERVER_INTERNAL_IP')}}"
  - worker_log_file: "{{lookup('env','WORKER_LOG_FILE')}}"
  - zone: "{{lookup('env','WORKER_ZONE')}}"
  tasks:
  - include: tasks/gcloud_create_instance.yml
  - include: tasks/gcloud_configure_instance_ssh.yml

- name: Set up new instance(s).
  hosts: new_instances
  remote_user: "{{lookup('env', 'WORKER_REMOTE_USER')}}"
  become_method: sudo
  become: yes
  roles:
  - {role: docker, when: "not {{lookup('env', 'WORKER_SKIP_INSTALLS')}}"}
  - {role: docker-py, when: "not {{lookup('env', 'WORKER_SKIP_INSTALLS')}}"}
  tasks:
  - include: tasks/gcloud_setup_loom_user.yml

- name: Set up the Loom worker on the new instance.
  hosts: new_instances
  become: yes
  remote_user: "{{lookup('env', 'WORKER_REMOTE_USER')}}"
  roles:
  - loom-worker
