---
- name: Create a new instance for the Loom server.
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
  - boot_disk_size_gb: "{{lookup('env','SERVER_DISK_SIZE')}}"
  - boot_disk_type: "{{lookup('env','SERVER_DISK_TYPE')}}"
  - gce_credential: "{{lookup('env','GCE_PEM_FILE_PATH')}}"
  - gce_email: "{{lookup('env','GCE_EMAIL')}}"
  - gce_ssh_key_file: "{{lookup('env', 'GCE_SSH_KEY_FILE')}}"
  - instance_image: "{{lookup('env','SERVER_VM_IMAGE')}}"
  - instance_name: "{{lookup('env','SERVER_NAME')}}"
  - instance_type: "{{lookup('env','SERVER_INSTANCE_TYPE')}}"
  - network: "{{lookup('env','SERVER_NETWORK')}}"
  - remote_user: "{{lookup('env','USER')}}"
  - subnetwork: "{{lookup('env','SERVER_CUSTOM_SUBNET')}}"
  - tags: "{{lookup('env','SERVER_TAGS')}}"
  - use_internal_ip: "{{lookup('env','CLIENT_USES_SERVER_INTERNAL_IP')}}"
  - zone: "{{lookup('env','SERVER_ZONE')}}"
  tasks:
  - include: tasks/gcloud_create_instance.yml
  - include: tasks/gcloud_configure_instance_ssh.yml

- name: Install docker
  hosts: new_instances
  become: yes
  roles:
  - {role: docker, when: "not {{lookup('env', 'SERVER_SKIP_INSTALLS')}}"}
  - {role: docker-py, when: "not {{lookup('env', 'SERVER_SKIP_INSTALLS')}}"}
  tasks:
  - include: tasks/gcloud_setup_loom_user.yml

- name: Set up the Loom server on the new instance. 
  hosts: new_instances
  become: yes
  become_user: loom
  roles:
  - loom-master

- name: Run the user-provided playbook.
  include: "{{lookup('env','RUN_AFTER_SERVER_CREATE_PLAYBOOK_PATH')}}"
