---
- name: Create a new instance for the Loom worker.
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include: tasks/gcloud_create_instance.yml
  - include: tasks/gcloud_configure_instance_ssh.yml

- name: Set up new instance(s).
  hosts: new_instances
  remote_user: {{ remote_user }}
  become_method: sudo
  become: yes
  roles:
  - {role: docker, when: "not {{lookup('env', 'WORKER_SKIP_INSTALLS')}}"}
  - {role: docker-py, when: "not {{lookup('env', 'WORKER_SKIP_INSTALLS')}}"}
  tasks:
  - include: tasks/gcloud_setup_loom_user.yml

- name: Set up the Loom worker on the new instance.
  hosts: new_instances
  become: yes
  become_user: loom
  roles:
  - loom-worker
