---
- name: Start the various components of a loom server
  hosts: localhost
  connection: local
  vars:
    # These vars only affect file locations in containers, hence
    # belong here rather than in the user-visible settings file
    nginx_conf_file: nginx.conf
    shared_settings_dir_in_container: /shared-settings

    # Define these vars for use by 'template' module
    LOOM_NGINX_INTERNAL_PORT: "{{ lookup('env', 'LOOM_NGINX_INTERNAL_PORT') }}"
    LOOM_NGINX_SERVER_NAME: "{{ lookup('env', 'LOOM_NGINX_SERVER_NAME') }}"
    LOOM_NGINX_WEBPORTAL_ROOT: "{{ lookup('env', 'LOOM_NGINX_WEBPORTAL_ROOT') }}"
    LOOM_NGINX_ACCESS_LOG: "{{ lookup('env', 'LOOM_NGINX_ACCESS_LOG') }}"
    LOOM_NGINX_ERROR_LOG: "{{ lookup('env', 'LOOM_NGINX_ERROR_LOG') }}"
    LOOM_MASTER_INTERNAL_PORT: "{{ lookup('env', 'LOOM_MASTER_INTERNAL_PORT') }}"
    LOOM_MASTER_CONTAINER_NAME: "{{ lookup('env', 'LOOM_MASTER_CONTAINER_NAME') }}"
    LOOM_SERVER_URL: "http://127.0.0.1:{{ lookup('env', 'LOOM_EXTERNAL_PORT') }}"

  tasks:

    - name: Start a MySQL database container
      docker_container:
        name: "{{ lookup('env', 'LOOM_MYSQL_CONTAINER_NAME') }}"
        hostname: "{{ lookup('env', 'LOOM_MYSQL_CONTAINER_NAME') }}"
        image: "{{ lookup('env', 'LOOM_MYSQL_IMAGE') }}"
        restart_policy: always
        api_version: auto
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: "{{lookup('env', 'LOOM_MYSQL_RANDOM_ROOT_PASSWORD')}}"
          MYSQL_DATABASE: "{{lookup('env', 'LOOM_MYSQL_DATABASE')}}"
          MYSQL_USER: "{{lookup('env', 'LOOM_MYSQL_USER')}}"
          MYSQL_PASSWORD: "{{lookup('env', 'LOOM_MYSQL_PASSWORD')}}"

    - name: Start a rabbitmq container to handle message passing for asynchronous tasks
      docker_container:
        name: "{{ lookup('env', 'LOOM_RABBITMQ_CONTAINER_NAME') }}"
        hostname: "{{ lookup('env', 'LOOM_RABBITMQ_CONTAINER_NAME') }}"
        image: "{{ lookup('env', 'LOOM_RABBITMQ_IMAGE') }}"
        restart_policy: always
        api_version: auto
        env:
          RABBITMQ_USER: "{{lookup('env', 'LOOM_RABBITMQ_GUEST')}}"
          RABBITMQ_PASSWORD: "{{lookup('env', 'LOOM_RABBITMQ_PASSWORD')}}"
          RABBITMQ_HOST: "{{lookup('env', 'LOOM_RABBITMQ_HOST')}}"
          RABBITMQ_PORT: "{{lookup('env', 'LOOM_RABBITMQ_PORT')}}"
          RABBITMQ_VHOST: "{{lookup('env', 'LOOM_RABBITMQ_VHOST')}}"

    - name: Start a container with celery workers to run asynchronous tasks
      docker_container:
        name: "{{ lookup('env', 'LOOM_WORKER_CONTAINER_NAME') }}"
        image: "{{ lookup('env', 'LOOM_DOCKER_IMAGE') }}"
        command: /loomengine/bin/run_worker.sh
        restart_policy: always
        api_version: auto
        env_file: "{{ lookup('env', 'LOOM_SHARED_SETTINGS_DIR') }}/{{ lookup('env', 'LOOM_SHARED_SETTINGS_FILE') }}"
        env:
          C_FORCE_ROOT: true
          LOOM_SHARED_SETTINGS_DIR: "{{ shared_settings_dir_in_container }}"
          LOOM_MYSQL_HOST: "{{lookup('env', 'LOOM_MYSQL_CONTAINER_NAME')}}"
          LOOM_RABBITMQ_HOST: "{{lookup('env', 'LOOM_RABBITMQ_CONTAINER_NAME')}}"

        volumes:
          - /loomengine/loomengine/portal
          - "{{ lookup('env', 'LOOM_SHARED_SETTINGS_DIR') }}:{{ shared_settings_dir_in_container }}"
        links:
          - "{{ lookup('env', 'LOOM_MYSQL_CONTAINER_NAME') }}"
          - "{{ lookup('env', 'LOOM_RABBITMQ_CONTAINER_NAME') }}"

    - name: Start a container with the Loom Master webserver
      docker_container:
        name: "{{ lookup('env', 'LOOM_MASTER_CONTAINER_NAME') }}"
        hostname: "{{ lookup('env', 'LOOM_MASTER_CONTAINER_NAME') }}"
        image: "{{ lookup('env', 'LOOM_DOCKER_IMAGE') }}"
        command: /loomengine/bin/run_master.sh
        restart_policy: always
        api_version: auto
        env_file: "{{ lookup('env', 'LOOM_SHARED_SETTINGS_DIR') }}/{{ lookup('env', 'LOOM_SHARED_SETTINGS_FILE') }}"
        env:
          LOOM_SHARED_SETTINGS_DIR: "{{ shared_settings_dir_in_container }}"
          LOOM_MYSQL_HOST: "{{lookup('env', 'LOOM_MYSQL_CONTAINER_NAME')}}"
          LOOM_RABBITMQ_HOST: "{{lookup('env', 'LOOM_RABBITMQ_CONTAINER_NAME')}}"
        volumes:
          - /loomengine/loomengine/portal
          - "{{ lookup('env', 'LOOM_SHARED_SETTINGS_DIR') }}:{{ shared_settings_dir_in_container }}"
        links:
          - "{{ lookup('env', 'LOOM_MYSQL_CONTAINER_NAME') }}"
          - "{{ lookup('env', 'LOOM_RABBITMQ_CONTAINER_NAME') }}"

    - name: Create a config file for the NGINX web server
      template:
        src: templates/local.nginx.conf
        dest: "{{ lookup('env', 'LOOM_SHARED_SETTINGS_DIR') }}/nginx.conf"

    - name: Start an NGINX server container
      docker_container:
        name: "{{ lookup('env', 'LOOM_NGINX_CONTAINER_NAME') }}"
        image: "{{ lookup('env', 'LOOM_NGINX_IMAGE') }}"
        restart_policy: always
        api_version: auto
        volumes:
          - "{{ lookup('env', 'LOOM_SHARED_SETTINGS_DIR') }}/nginx.conf:/etc/nginx/conf.d/default.conf"
        volumes_from:
          - "{{ lookup('env', 'LOOM_MASTER_CONTAINER_NAME') }}"
        links:
          - "{{ lookup('env', 'LOOM_MASTER_CONTAINER_NAME') }}"
        ports:
          - "{{ lookup('env', 'LOOM_EXTERNAL_PORT') }}:{{ lookup('env', 'LOOM_NGINX_INTERNAL_PORT') }}"

    - name: Create server config file so command line client knows where to find server
      template:
        src: templates/local.server.cfg
        dest: "{{ LOOM_SETTINGS_HOME }}/server.cfg"

    - name: Wait for Loom server port to be available
      wait_for: port="{{ lookup('env', 'LOOM_EXTERNAL_PORT') }}"

    - name: Wait for Loom server to return OK status. (FAILED - RETRYING messages are normal)
      uri: "url={{ LOOM_SERVER_URL }}/api/status/ validate_certs=False"
      register: response
      until: response.status == 200
      retries: 30
      delay: 10
