---
- name: Create a new instance for the Loom worker.
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - vars/gcloud_worker.yml
  tasks:
  - include: tasks/gcloud_create_instance.yml
  - include: tasks/gcloud_configure_instance_ssh.yml

- name: Install Docker on the Loom worker.
  hosts: new_instances
  remote_user: "{{lookup('env', 'WORKER_REMOTE_USER')}}"
  become_method: sudo
  become: yes
  roles:
  - {role: docker, when: "not {{lookup('env', 'LOOM_GCLOUD_WORKER_SKIP_INSTALLS')}}"}
  - {role: docker-py, when: "not {{lookup('env', 'LOOM_GCLOUD_WORKER_SKIP_INSTALLS')}}"}
  tasks:
  - include: tasks/gcloud_create_docker_group.yml

- name: Set up the Loom worker on the new instance.
  hosts: new_instances
  become: yes
  remote_user: "{{lookup('env', 'WORKER_REMOTE_USER')}}"
  vars_files:
  - vars/gcloud_worker.yml
  tasks:
  - include: tasks/gcloud_setup_worker.yml
