---
- name: Create a new instance for the Loom server.
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - vars/common.yml
  - vars/gcloud.yml
  tasks:
  - include: tasks/gcloud_create_instance.yml
  - include: tasks/gcloud_configure_instance_ssh.yml

- name: Create connection settings file now that we have a server IP, and collect admin files on the client.
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - vars/common.yml
  - vars/gcloud.yml
  vars:
  - server_url: "{{server_protocol}}://{{groups['new_instances'][0]}}:{{server_port}}"
  tasks:
  - include: tasks/create_connection_settings.yml

- name: Create storage bucket. Ignore error if bucket already exists.
  hosts: localhost
  vars_files:
  - vars/common.yml
  - vars/gcloud.yml
  tasks:
  - include: tasks/create_google_storage_bucket.yml

- name: Install Docker on the Loom server.
  hosts: new_instances
  become: yes
  roles:
  - {role: docker, when: "not {{lookup('env', 'LOOM_GCLOUD_SERVER_SKIP_INSTALLS')|bool}}"}
  - {role: docker-py, when: "not {{lookup('env', 'LOOM_GCLOUD_SERVER_SKIP_INSTALLS')|bool}}"}
  tasks:
  - include: tasks/gcloud_create_docker_group.yml

- name: Set up the Loom server on the new instance.
  hosts: new_instances
  become: yes
  become_user: loom
  vars_files:
  - vars/common.yml
  - vars/gcloud.yml
  tasks:
  - include: tasks/gcloud_setup_server.yml

- name: Start the Loom server.
  hosts: new_instances
  become: yes
  become_user: loom
  vars_files:
  - vars/common.yml
  - vars/gcloud.yml
  vars:
  - server_url: "{{lookup('ini', 'LOOM_SERVER_URL type=properties file='+settings_home+'/'+connection_settings_file)}}"
  tasks:
  - include: tasks/start_server.yml
