---
- name: Stop all the components of a loom server
  hosts: "{{lookup('env','LOOM_SERVER_NAME')}}"
  become: yes
  vars_files:
    - vars/gcloud_server.yml
  tasks:
    - include: tasks/stop_containers.yml
