---
- name: Run the Loom task runner on the specified worker instance.
  hosts: "{{lookup('env','WORKER_INSTANCE_NAME')}}"
  remote_user: loom
  become: yes
  become_method: sudo
  vars_files:
  - vars/gcloud_worker.yml  
  tasks:
  - name: Run the Loom task runner.
    docker_container:
      name: loom
      image: "{{loom_docker_image}}"
      volumes: ["{{remote_loom_settings_path}}:/root/.loom", "{{scratch_disk_mount_point}}:{{scratch_disk_mount_point}}", "/var/run/docker.sock:/var/run/docker.sock"]
      api_version: auto
      command: /bin/bash -c 'source /opt/loom-env/bin/activate && loom-taskrunner --run_attempt_id {{task_run_attempt_id}} --master_url {{master_url}} --log_level {{log_level}} --log_file {{worker_log_file}}'
