---
- name: Create a new instance for the Loom server.
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - vars/gcloud.yml
  tasks:
  - include: tasks/gcloud_create_instance.yml
  - include: tasks/gcloud_configure_instance_ssh.yml

- name: Install Docker on the Loom server.
  hosts: new_instances
  become: yes
  roles:
  - {role: docker, when: "not {{lookup('env', 'LOOM_GCLOUD_SERVER_SKIP_INSTALLS')}}"}
  - {role: docker-py, when: "not {{lookup('env', 'LOOM_GCLOUD_SERVER_SKIP_INSTALLS')}}"}
  tasks:
  - include: tasks/gcloud_setup_loom_user.yml

- name: Set up the Loom server on the new instance.
  hosts: new_instances
  become: yes
  become_user: loom
  vars_files:
  - vars/gcloud.yml
  tasks:
  - include: tasks/gcloud_setup_server.yml

- name: Start the Loom server.
  hosts: new_instances
  become: yes
  become_user: loom
  vars_files:
  - vars/gcloud.yml
  vars:
    loom_server_url: "{{hostvars[host]['loom_server_url']}}"
  tasks:
  - include: tasks/start_server.yml
