---
- name: Delete the Loom server.
  hosts: localhost
  connection: local
  vars_files:
  - vars/common.yml
  - vars/gcloud.yml
  tasks:
  - name: Delete the Loom server.
    local_action:
      module: gce
      state: 'absent'
      instance_names: "{{instance_name}}"
      zone: "{{zone}}"
      credentials_file: "{{gce_credential}}"
      project_id: "{{gce_project}}"
      service_account_email: "{{gce_email}}"
