---
- name: Delete the named worker instance.
  hosts: localhost
  connection: local
  vars_files:
  - vars/common.yml
  - vars/gcloud_worker.yml
  tasks:
  - include: tasks/gcloud_delete_instance.yml
