---
- name: Start the various components of a loom server
  hosts: localhost
  connection: local
  vars_files:
    - vars/local.yml
  tasks:
    - include: tasks/create_connection_settings.yml
    - include: tasks/start_server.yml
