---
- name: Run the Loom task runner on localhost.
  hosts: localhost
  connection: local
  vars_files:
    - vars/common.yml
    - vars/local.yml
  vars:
    task_attempt_id: "{{lookup('env', 'LOOM_TASK_ATTEMPT_ID')}}"
  tasks:
  - name: Run the Loom task runner.
    docker_container:
      name: "{{taskrunner_container_name}}-{{task_attempt_id}}"
      image: "{{loom_docker_image}}"
      volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
      api_version: auto
      command: /bin/bash -c 'loom-taskrunner --task_attempt_id {{task_attempt_id}} --master_url {{server_url}} --log_level {{log_level}} --log_file {{worker_log_file}}'
