# Playbook that deploys xppf master and workers
# TODO: upload to ansible galaxy

- hosts: xppf_master
  tasks:
  - name: Install git, pip, and virtualenv
    apt:
      pkg: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
      - git
      - python-pip
      - python-virtualenv
  - name: Pull xppf from GitHub
    git: repo=https://github.com/StanfordBioinformatics/xppf.git
         dest=/opt/xppf/xppf
  - name: Set up virtualenv for xppf and install dependencies
    pip: virtualenv=/opt/xppf/env
         requirements=/opt/xppf/xppf/master/requirements.txt
  - name: Start xppf webserver and daemon
    shell: source /opt/xppf/env/bin/activate;export RACK_ENV=development;/opt/xppf/xppf/master/manage.py migrate;./xppfserver start
    args:
      executable: /bin/bash
      chdir: /opt/xppf/xppf/bin

# docker_ubuntu already installs git and pip
- hosts: xppf_worker
  tasks:
  - name: Install virtualenv
    apt:
      pkg: python-virtualenv
      state: latest
      update_cache: yes
  - name: Pull xppf from GitHub
    git: repo=https://github.com/StanfordBioinformatics/xppf.git
         dest=/opt/xppf/xppf
  - name: Set up virtualenv for xppf and install dependencies
    pip: virtualenv=/opt/xppf/env
         requirements=/opt/xppf/xppf/worker/requirements.txt
