LOOM_CREATE_SERVER_PLAYBOOK: local_create_server.yaml
LOOM_ANSIBLE_INVENTORY: localhost,

LOOM_MASTER_HOST: loom-master

LOOM_MYSQL_CONTAINER_NAME: loom-mysql
LOOM_MYSQL_HOST: loom-mysql
LOOM_MYSQL_IMAGE: mysql:5.7.17
LOOM_MYSQL_RANDOM_ROOT_PASSWORD: true
LOOM_MYSQL_USER: loom
LOOM_MYSQL_DATABASE: loom
LOOM_MYSQL_PASSWORD: loompass

LOOM_RABBITMQ_CONTAINER_NAME: loom-rabbitmq
LOOM_RABBITMQ_HOST: loom-rabbitmq
LOOM_RABBITMQ_IMAGE: rabbitmq:3.6.6
LOOM_RABBITMQ_USER: guest
LOOM_RABBITMQ_PASSWORD: guest
LOOM_RABBITMQ_PORT: 5672
LOOM_RABBITMQ_VHOST: /

LOOM_NGINX_CONTAINER_NAME: loom-nginx
LOOM_NGINX_HOST: loom-nginx
LOOM_NGINX_IMAGE: nginx:1.11
LOOM_NGINX_TEMPLATE: local.nginx.conf
LOOM_NGINX_INTERNAL_PORT: 80
LOOM_NGINX_EXTERNAL_PORT: 80
LOOM_NGINX_SERVER_NAME: localhost
LOOM_NGINX_ACCESS_LOG: /var/log/nginx/loom.access.log
LOOM_NGINX_ERROR_LOG: /var/log/nginx/loom.error.log
LOOM_NGINX_WEBPORTAL_ROOT: /loomengine/loomengine/portal

LOOM_MASTER_CONTAINER_NAME: loom-master
LOOM_MASTER_ALLOWED_HOSTS: 127.0.0.1
LOOM_DOCKER_IMAGE: loomengine/loom:nopolymorphic

LOOM_WORKER_CONTAINER_NAME: loom-worker



LOOM_RABBITMQ_HOSTNAME: loom-rabbitmq