LOOM_SERVER_NAME: local-loom-server

LOOM_START_SERVER_PLAYBOOK: local_start_server.yaml
LOOM_STOP_SERVER_PLAYBOOK: local_stop_server.yaml
LOOM_DELETE_SERVER_PLAYBOOK: local_delete_server.yaml

LOOM_ANSIBLE_INVENTORY: localhost,
LOOM_LOG_LEVEL: info
LOOM_DOCKER_IMAGE: loomengine/loom:nopolymorphic

LOOM_MASTER_CONTAINER_NAME: loom-master-container
LOOM_MASTER_ALLOWED_HOSTS: 127.0.0.1
LOOM_MASTER_INTERNAL_IP: 0.0.0.0
LOOM_MASTER_INTERNAL_PORT: 8000

LOOM_WORKER_CONTAINER_NAME: loom-worker-container

LOOM_MYSQL_CONTAINER_NAME: loom-mysql-container
LOOM_MYSQL_IMAGE: mysql:5.7.17
LOOM_MYSQL_RANDOM_ROOT_PASSWORD: true
LOOM_MYSQL_USER: loom
LOOM_MYSQL_DATABASE: loom
LOOM_MYSQL_PASSWORD: loompass

LOOM_RABBITMQ_CONTAINER_NAME: loom-rabbitmq-container
LOOM_RABBITMQ_IMAGE: rabbitmq:3.6.6
LOOM_RABBITMQ_USER: guest
LOOM_RABBITMQ_PASSWORD: guest
LOOM_RABBITMQ_PORT: 5672
LOOM_RABBITMQ_VHOST: /

LOOM_NGINX_CONTAINER_NAME: loom-nginx-container
LOOM_NGINX_IMAGE: nginx:1.11
LOOM_NGINX_TEMPLATE: local.nginx.conf
LOOM_NGINX_INTERNAL_PORT: 80
LOOM_NGINX_SERVER_NAME: localhost
LOOM_NGINX_ACCESS_LOG: /var/log/nginx/loom.access.log
LOOM_NGINX_ERROR_LOG: /var/log/nginx/loom.error.log
LOOM_NGINX_WEBPORTAL_ROOT: /loomengine/loomengine/portal

LOOM_EXTERNAL_PORT: 8000
