  - stat: path=~/.ssh/google_compute_engine.pub
    register: public_key
  - name: Create SSH key if it doesn't exist
    shell: ssh-keygen -q -t rsa -f ~/.ssh/google_compute_engine -P "" -C "{{lookup('env','USER')}}"
    when: public_key.stat.exists == False
  - name: Add SSH key to instance metadata
    shell: "gcloud compute instances add-metadata {{instance_name}} --metadata ssh-keys=\"{{lookup('env','USER')}}: {{ lookup('file', '~/.ssh/google_compute_engine.pub') }}\""
  - name: Wait for SSH port to be available.
    wait_for: host={{ (use_internal_ip) | ternary(item.private_ip, item.public_ip) }} port=22 delay=10 timeout=300 search_regex=OpenSSH
    with_items: '{{ gce_result.instance_data }}'
