  - stat: path="{{gce_ssh_key_file}}"
    register: public_key_file
  - name: Create SSH key if it doesn't exist
    shell: ssh-keygen -q -t rsa -f "{{gce_ssh_key_file}}" -P "" -C {{ remote_user }}
    when: public_key_file.stat.exists == False
  - name: Read SSH key
    shell: cat "{{gce_ssh_key_file}}.pub"
    register: public_key_cat
  - name: Add SSH key to instance metadata
    shell: "gcloud compute instances add-metadata {{instance_name}} --zone {{zone}} --metadata ssh-keys=\"{{ remote_user }}: {{ public_key_cat.stdout }}\""
  - name: Wait for SSH port to be available.
    wait_for: host={{ (use_internal_ip) | ternary(item.private_ip, item.public_ip) }} port=22 delay=10 timeout=300 search_regex=OpenSSH
    with_items: '{{ gce_result.instance_data }}'
