  - name: Create a filesystem on the scratch disk.
    filesystem: fstype=ext4 dev={{scratch_disk_device_path}} force=no
  - name: Create the scratch disk mount point.
    file: path={{scratch_disk_mount_point}} state=directory
  - name: Mount the scratch disk at the mount point.
    mount: name={{scratch_disk_mount_point}} fstype=ext4 src={{scratch_disk_device_path}} state=mounted
  - name: Pull Loom Docker image.
    docker_image: name={{loom_docker_image}} api_version=auto
  - name: Pull task run Docker image.
    docker_image: name={{task_run_docker_image}} api_version=auto
