  - name: Run the Loom task runner.
    docker_container:
      name: "{{taskrunner_container_name}}-{{task_attempt_id}}"
      image: "{{loom_docker_image}}"
      volumes:  "{{[ /var/run/docker.sock~':'~/var/run/docker.sock, \
                 taskrunner_host_working_dir~':'~taskrunner_container_working_dir, \
                 storage_root~':'~storage_root if lower(storage_type) == 'local'] \
                 | reject('undefined') | list}}"
      api_version: auto
      network_mode: host
      command: /bin/bash -c 'loom-taskrunner --task_attempt_id {{task_attempt_id}} --master_url {{server_url}} --log_level {{log_level}} --log_file {{taskrunner_log_file}} --host_working_dir {{taskrunner_host_working_dir}} --container_working_dir {{taskrunner_container_working_dir}}'
