---
- name: Start the Loom server.
  hosts: "{{lookup('env','SERVER_NAME')}}"
  become: yes
  become_method: sudo
  vars:
    remote_loom_settings_path: "{{ansible_env.HOME}}/{{lookup('env', 'LOOM_HOME_SUBDIR')}}"
  tasks:
  - name: Start the Loom server.
    shell: source /opt/loom/bin/activate; loom server set local; loom server start
    args:
      executable: /bin/bash
  - name: Start NGINX.
    docker_container: name=loom-nginx image=nginx network_mode=host volumes={{remote_loom_settings_path}}/nginx.conf:/etc/nginx/conf.d/default.conf,/var/log/nginx:/var/log/nginx api_version=auto
