---
- name: Stop the Loom server.
  hosts: "{{lookup('env','SERVER_NAME')}}"
  become: yes
  become_method: sudo
  tasks:
  - name: Stop the Loom server.
    shell: source /opt/loom/bin/activate; loom server set local; loom server stop
    args:
      executable: /bin/bash
