---
- name: Stop the Loom server.
  hosts: "{{lookup('env','SERVER_NAME')}}"
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: /opt/loom/bin/python # Use virtualenv.
  tasks:
  - name: Stop the Loom server.
    shell: source /opt/loom/bin/activate; loom server set local; loom server stop
    args:
      executable: /bin/bash
