---
- name: Create a Google Cloud Storage bucket. 
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    gce_bucket: "{{lookup('env', 'GCE_BUCKET')}}"
  tasks:
  - name: Create storage bucket. Ignore error if bucket already exists.
    shell: gsutil mb gs://{{gce_bucket}}/
    ignore_errors: yes 
