---
- name: Stop the Loom server.
  hosts: "{{lookup('env','SERVER_NAME')}}"
  become: yes
  become_method: sudo
  tasks:
  - name: Notify the Loom server to shut down.
    docker_container:
      name: loom
      api_version: auto
      command: [/bin/bash, -c, 'source /opt/loom/bin/activate && loom server stop']
    ignore_errors: yes
  - name: Stop the Docker container running the Loom server.
    docker_container:
      name: loom
      api_version: auto
      state: stopped

