---
- name: Create a new instance for the Loom server.
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
  - include: vars/gcloud_create_server.yml
  tasks:
  - include: tasks/gcloud_create_instance.yml

- name: Set up the Loom server on the new instance. 
  hosts: new_instances
  become: yes
  roles:
  - {role: docker, when: "{{lookup('env', 'SERVER_SKIP_INSTALLS')}}"}
  - {role: docker-py, when: "{{lookup('env', 'SERVER_SKIP_INSTALLS')}}"}
  - loom-master

- name: Run the user-provided playbook.
  include: "{{lookup('env','RUN_AFTER_SERVER_CREATE_PLAYBOOK_PATH')}}"
