---
- name: Start the Loom server.
  hosts: "{{lookup('env','SERVER_NAME')}}"
  become: yes
  vars:
    remote_loom_settings_path: /home/loom/{{lookup('env', 'LOOM_HOME_SUBDIR')}}
    local_loom_settings_path: "{{lookup('env','HOME')}}/{{lookup('env', 'LOOM_HOME_SUBDIR')}}"
    docker_full_name: "{{lookup('env', 'DOCKER_FULL_NAME')}}"
  tasks:
  - name: Start the Loom server.
    docker_container:
      name: loom
      image: "{{docker_full_name}}"
      ports: 8000:8000
      volumes: "{{remote_loom_settings_path}}"
      restart_policy: always
      api_version: auto
      user: loom
      command: [/bin/bash, -c, 'source /opt/loom/bin/activate && loom server set local && loom server start --foreground']
  - name: Start NGINX.
    docker_container:
      name: nginx
      image: nginx
      network_mode: host
      volumes: "{{remote_loom_settings_path}}/nginx.conf:/etc/nginx/conf.d/default.conf,/var/log/nginx:/var/log/nginx,{{remote_loom_settings_path}}/ssl:/etc/nginx/ssl"
      restart_policy: always
      api_version: auto
#  - name: Copy newly generated TLS/SSL certificate to client.
#    fetch: src={{remote_loom_settings_path}}/ssl/ssl.crt dest={{local_loom_settings_path}}/ flat=yes
#  - name: Copy newly generated TLS/SSL key to client.
#    fetch: src={{remote_loom_settings_path}}/ssl/ssl.key dest={{local_loom_settings_path}}/ flat=yes
