---
- name: Create a new instance for the Loom server.
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    server_name: "{{lookup('env','SERVER_NAME')}}"
    server_zone: "{{lookup('env','SERVER_ZONE')}}"
    server_vm_image: "{{lookup('env','SERVER_VM_IMAGE')}}"
    server_instance_type: "{{lookup('env','SERVER_INSTANCE_TYPE')}}"
    server_network: "{{lookup('env','SERVER_NETWORK')}}"
    server_tags: "{{lookup('env','SERVER_TAGS')}}"
    server_disk_type: "{{lookup('env','SERVER_DISK_TYPE')}}"
    server_disk_size: "{{lookup('env','SERVER_DISK_SIZE')}}"
    docker_name: "{{lookup('env','DOCKER_NAME')}}"
    docker_tag: "{{lookup('env','DOCKER_TAG')}}"
  tasks:
  - name: Create a boot disk with the same name as the server instance.
    gce_pd: name={{server_name}} image={{server_vm_image}} disk_type={{server_disk_type}} size_gb={{server_disk_size}} zone={{server_zone}} mode=READ_WRITE
  - name: Boot up a new instance using the just-created boot disk.
    gce: name={{server_name}} disks={{server_name}} zone={{server_zone}} machine_type={{server_instance_type}} network={{server_network}} service_account_permissions=cloud-platform tags={{server_tags|default(omit)}}
    register: gce_result
  - name: Wait for SSH to come up.
    wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
    with_items: '{{ gce_result.instance_data }}'
  - name: Add host to new_instances.
    add_host: hostname={{ item.public_ip }} groupname=new_instances
    with_items: '{{ gce_result.instance_data }}'
  - name: Save Loom Docker image to a tar file.
    docker_image: name={{docker_name}} tag={{docker_tag}} archive_path=/tmp/loom.tar api_version=auto

- name: Set up the Loom server on the new instance. 
  hosts: new_instances
  become: yes
  become_method: sudo
  roles:
  - loom_master
  vars:
    docker_name: "{{lookup('env','DOCKER_NAME')}}"
    docker_tag: "{{lookup('env','DOCKER_TAG')}}"
  tasks:
  - name: Upload tar file.
    copy: src=/tmp/loom.tar dest=/tmp/loom.tar
  - name: Load docker image from tar file.
    docker_image: name={{docker_name}} tag={{docker_tag}} load_path=/tmp/loom.tar api_version=auto

- name: Delete Loom Docker tar file.
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Delete Loom Docker tar file.  
    file: path=/tmp/loom.tar state=absent
