- name: Create a boot disk with the same name as the server instance.
  gce_pd: name={{server_name}} image={{server_vm_image}} disk_type={{server_disk_type}} size_gb={{server_disk_size}} zone={{server_zone}} mode=READ_WRITE
- name: Boot up a new instance using the just-created boot disk.
  gce: name={{server_name}} disks={{server_name}} zone={{server_zone}} machine_type={{server_instance_type}} network={{server_network}} service_account_permissions=cloud-platform tags={{server_tags|default(omit)}}
  register: gce_result
- name: Wait for SSH to come up.
  wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
  with_items: '{{ gce_result.instance_data }}'
- name: Add host to new_instances.
  add_host: hostname={{ item.public_ip }} groupname=new_instances
  with_items: '{{ gce_result.instance_data }}'
