server_settings_home: "{{ansible_env.HOME}}/.loom"

ssh_private_key_file_create_new: "{{lookup('env', 'LOOM_ANSILE_SSH_PRIVATE_KEY_FILE_CREATE_NEW') | bool}}"
ssh_private_key_file: "{{lookup('env', 'LOOM_ANSIBLE_SSH_PRIVATE_KEY_FILE')}}"

# GCE settings
boot_disk_type: "{{lookup('env','LOOM_GCLOUD_SERVER_BOOT_DISK_TYPE')}}"
boot_disk_size_gb: "{{lookup('env','LOOM_GCLOUD_SERVER_BOOT_DISK_SIZE_GB')}}"
gce_email: "{{lookup('env','GCE_EMAIL')}}"
gce_credential: "{{lookup('env','GCE_PEM_FILE_PATH')}}"
instance_name: "{{lookup('env','LOOM_SERVER_NAME')}}"
instance_image: "{{lookup('env','LOOM_GCLOUD_SERVER_INSTANCE_IMAGE')}}"
instance_type: "{{lookup('env','LOOM_GCLOUD_SERVER_INSTANCE_TYPE')}}"
network: "{{lookup('env','LOOM_GCLOUD_SERVER_NETWORK')}}"
remote_user: "{{lookup('env','USER')}}"
subnetwork: "{{lookup('env','LOOM_GCLOUD_SERVER_SUBNETWORK')}}"
tags: "{{lookup('env','LOOM_GCLOUD_SERVER_TAGS')}}"
ansible_uses_internal_ip: "{{lookup('env','LOOM_GCLOUD_CLIENT_USES_SERVER_INTERNAL_IP')}}"
external_ip: "{{lookup('env','LOOM_GCLOUD_SERVER_EXTERNAL_IP')}}"
zone: "{{lookup('env','LOOM_GCLOUD_SERVER_ZONE')}}"
