  - boot_disk_size_gb: "{{lookup('env','LOOM_GCLOUD_WORKER_BOOT_DISK_SIZE_GB')}}"
  - boot_disk_type: "{{lookup('env','LOOM_GCLOUD_WORKER_BOOT_DISK_TYPE')}}"
  - external_ip: "{{lookup('env','LOOM_GCLOUD_WORKER_EXTERNAL_IP')}}"
  - gce_credential: "{{lookup('env','GCE_PEM_FILE_PATH')}}"
  - gce_email: "{{lookup('env','GCE_EMAIL')}}"
  - gce_ssh_key_file: "{{lookup('env', 'GCE_SSH_KEY_FILE')}}"
  - instance_image: "{{lookup('env','LOOM_GCLOUD_WORKER_INSTANCE_IMAGE')}}"
  - instance_name: "{{lookup('env','WORKER_INSTANCE_NAME')}}"
  - instance_type: "{{lookup('env','LOOM_GCLOUD_WORKER_INSTANCE_TYPE')}}"
  - log_level: "{{lookup('env','LOOM_LOG_LEVEL')}}"
  - loom_docker_image: "{{lookup('env','LOOM_DOCKER_IMAGE')}}"
  - master_url: "{{lookup('env','MASTER_URL_FOR_WORKER')}}"
  - network: "{{lookup('env','LOOM_GCLOUD_WORKER_NETWORK')}}"
  - remote_loom_settings_path: "{{ansible_env.HOME}}/{{lookup('env', 'LOOM_SETTINGS_SUBDIR')}}"
  - remote_user: "{{lookup('env', 'WORKER_REMOTE_USER')}}"
  - scratch_disk_device_path: "{{lookup('env','WORKER_SCRATCH_DISK_DEVICE_PATH')}}"
  - scratch_disk_mount_point: "{{lookup('env','LOOM_GCLOUD_WORKER_SCRATCH_DISK_MOUNT_POINT')}}"
  - scratch_disk_name: "{{lookup('env','WORKER_SCRATCH_DISK_NAME')}}"
  - scratch_disk_size_gb: "{{lookup('env','LOOM_GCLOUD_WORKER_SCRATCH_DISK_SIZE_GB')}}"
  - scratch_disk_type: "{{lookup('env','LOOM_GCLOUD_WORKER_SCRATCH_DISK_TYPE')}}"
  - subnetwork: "{{lookup('env','LOOM_GCLOUD_WORKER_SUBNETWORK')}}"
  - tags: "{{lookup('env','LOOM_GCLOUD_WORKER_TAGS')}}"
  - task_run_attempt_id: "{{lookup('env', 'TASK_RUN_ATTEMPT_ID')}}"
  - task_run_docker_image: "{{lookup('env','TASK_RUN_DOCKER_IMAGE')}}"
  - use_internal_ip: "{{lookup('env','LOOM_GCLOUD_WORKER_USES_SERVER_INTERNAL_IP')}}"
  - worker_log_file: "{{lookup('env','WORKER_LOG_FILE')}}"
  - zone: "{{lookup('env','LOOM_GCLOUD_WORKER_ZONE')}}"
