server_settings_home: "{{ansible_env.HOME}}/.loom"

remote_user: "{{lookup('env','USER')}}"
ssh_private_key_file_path: "{{ansible_env.HOME}}/.ssh/{{lookup('env', 'LOOM_SSH_PRIVATE_KEY_NAME')}}"
worker_ssh_private_key_file_path: "{{settings_home}}/{{admin_files_dir}}/loom_worker_id_rsa"
ansible_uses_internal_ip: "{{lookup('env','LOOM_GCLOUD_CLIENT_USES_SERVER_INTERNAL_IP')}}"
worker_uses_internal_ip: "{{lookup('env','LOOM_GCLOUD_WORKER_USES_SERVER_INTERNAL_IP')}}"
worker_connection_settings_file: "{{lookup('env','LOOM_GCLOUD_WORKER_CONNECTION_SETTINGS_FILE')}}"

# GCE settings
boot_disk_type: "{{lookup('env','LOOM_GCLOUD_SERVER_BOOT_DISK_TYPE')}}"
boot_disk_size_gb: "{{lookup('env','LOOM_GCLOUD_SERVER_BOOT_DISK_SIZE_GB')}}"
gce_credential: "{{server_settings_home}}/{{admin_files_dir}}/{{lookup('env','LOOM_GCE_PEM_FILE')}}"
gce_email: "{{lookup('env','LOOM_GCE_EMAIL')}}"
gce_project: "{{lookup('env','LOOM_GCE_PROJECT')}}"
instance_name: "{{lookup('env','LOOM_SERVER_NAME')}}"
instance_image: "{{lookup('env','LOOM_GCLOUD_SERVER_INSTANCE_IMAGE')}}"
instance_type: "{{lookup('env','LOOM_GCLOUD_SERVER_INSTANCE_TYPE')}}"
network: "{{lookup('env','LOOM_GCLOUD_SERVER_NETWORK')}}"
subnetwork: "{{lookup('env','LOOM_GCLOUD_SERVER_SUBNETWORK')}}"
tags: "{{lookup('env','LOOM_GCLOUD_SERVER_TAGS')}}"
external_ip: "{{lookup('env','LOOM_GCLOUD_SERVER_EXTERNAL_IP')}}"
zone: "{{lookup('env','LOOM_GCLOUD_SERVER_ZONE')}}"
