# General settings
loom_client_settings_home: "{{ lookup('env', 'LOOM_SETTINGS_HOME') }}"
loom_client_admin_files_full_path: "\
  {{ loom_client_settings_home }}\
  /{{ lookup('env', 'LOOM_ADMIN_FILES_DIR') }}"
loom_client_admin_settings_full_path: "\
  {{ loom_client_settings_home }}\
  /{{ lookup('env', 'LOOM_ADMIN_SETTINGS_FILE') }}"
loom_server_settings_home: "{{loom_client_settings_home}}"
loom_server_admin_files_full_path: "{{loom_client_admin_files_full_path}}"
loom_server_admin_settings_full_path: "{{loom_client_admin_settings_full_path}}"
loom_connection_settings_full_path: "\
  {{ loom_client_settings_home }}\
  /{{ lookup('env', 'LOOM_CONNECTION_SETTINGS_FILE') }}"
loom_settings_home_in_container: /loom-settings

loom_storage_root: "{{ lookup('env', 'LOOM_STORAGE_ROOT') }}"
loom_storage_root_in_container: /loom-storage
loom_static_root: "{{ lookup('env', 'LOOM_STATIC_ROOT') }}"

loom_storage_type: "{{lookup('env','LOOM_STORAGE_TYPE')}}"
loom_docker_image: "{{ lookup('env', 'LOOM_DOCKER_IMAGE') }}"
loom_server_url: "http://127.0.0.1:{{ lookup('env', 'LOOM_EXTERNAL_PORT') }}"
loom_external_port: "{{ lookup('env', 'LOOM_EXTERNAL_PORT') }}"

# MySQL container settings
loom_mysql_create_docker_container: "{{lookup('env', 'LOOM_MYSQL_CREATE_DOCKER_CONTAINER') | bool}}"
loom_mysql_image: "{{ lookup('env', 'LOOM_MYSQL_IMAGE') }}"
loom_mysql_container_name: "\
  {{ lookup('env', 'LOOM_SERVER_NAME') }}\
  {{ lookup('env', 'LOOM_MYSQL_CONTAINER_NAME_SUFFIX') }}"
loom_mysql_random_root_password: >
  {{ lookup('env', 'LOOM_MYSQL_RANDOM_ROOT_PASSWORD') }}
loom_mysql_database: "{{lookup('env', 'LOOM_MYSQL_DATABASE')}}"
loom_mysql_user: "{{lookup('env', 'LOOM_MYSQL_USER')}}"
loom_mysql_password: "{{lookup('env', 'LOOM_MYSQL_PASSWORD')}}"
loom_mysql_host: "{{loom_mysql_container_name}}"

# Rabbitmq container settings
loom_rabbitmq_image: "{{ lookup('env', 'LOOM_RABBITMQ_IMAGE') }}"
loom_rabbitmq_container_name: "\
  {{ lookup('env', 'LOOM_SERVER_NAME') }}\
  {{ lookup('env', 'LOOM_RABBITMQ_CONTAINER_NAME_SUFFIX') }}"
loom_rabbitmq_user: "{{lookup('env', 'LOOM_RABBITMQ_USER')}}"
loom_rabbitmq_password: "{{lookup('env', 'LOOM_RABBITMQ_PASSWORD')}}"
loom_rabbitmq_host: "{{lookup('env', 'LOOM_RABBITMQ_HOST')}}"
loom_rabbitmq_port: "{{lookup('env', 'LOOM_RABBITMQ_PORT')}}"
loom_rabbitmq_vhost: "{{lookup('env', 'LOOM_RABBITMQ_VHOST')}}"

# Celery worker container settings
loom_worker_container_name: "\
  {{ lookup('env', 'LOOM_SERVER_NAME') }}\
  {{ lookup('env', 'LOOM_WORKER_CONTAINER_NAME_SUFFIX') }}"

# Celery scheuler container settings
loom_scheduler_container_name: "\
  {{ lookup('env', 'LOOM_SERVER_NAME') }}\
  {{ lookup('env', 'LOOM_SCHEDULER_CONTAINER_NAME_SUFFIX') }}"

# NGINX container settings
loom_nginx_image: "{{ lookup('env', 'LOOM_NGINX_IMAGE') }}"
loom_nginx_container_name: "\
  {{ lookup('env', 'LOOM_SERVER_NAME') }}\
  {{ lookup('env', 'LOOM_NGINX_CONTAINER_NAME_SUFFIX') }}"
loom_nginx_conf_file: "{{ loom_server_admin_files_full_path }}/nginx.conf"
loom_nginx_internal_port: "{{ lookup('env', 'LOOM_NGINX_INTERNAL_PORT') }}"
loom_nginx_server_name: "{{ lookup('env', 'LOOM_NGINX_SERVER_NAME') }}"
loom_nginx_webportal_root: "{{ lookup('env', 'LOOM_NGINX_WEBPORTAL_ROOT') }}"
loom_nginx_access_log: "{{ lookup('env', 'LOOM_NGINX_ACCESS_LOG') }}"
loom_nginx_error_log: "{{ lookup('env', 'LOOM_NGINX_ERROR_LOG') }}"

# Loom master container settings
loom_master_container_name: "\
  {{ lookup('env', 'LOOM_SERVER_NAME') }}\
  {{ lookup('env', 'LOOM_MASTER_CONTAINER_NAME_SUFFIX') }}"
loom_master_internal_port: "{{ lookup('env', 'LOOM_MASTER_INTERNAL_PORT') }}"
